/**
 * `pnpm check:bundle` — does anything a browser receives carry a credential?
 *
 * This is the half of T023's done criterion that a source-level test cannot
 * reach. `env-discipline.test.ts` proves nobody wrote `import.meta.env.SECRET`;
 * this proves the thing that actually ships is clean.
 *
 * The two are not redundant. On 2026-09-15 the sources looked reasonable and
 * the build had the password inlined. Checking the artefact is checking the
 * claim rather than a proxy for it.
 *
 * ## Two surfaces, because one of them is easy to forget
 *
 *  1. **Static assets.** Client JS and CSS, where a build-time substitution
 *     lands. Found by building with marker values and searching the output.
 *  2. **The rendered HTML.** With `output: 'server'` every page is generated by
 *     a function at request time, so a secret interpolated into the page — a
 *     `<script>` with a key in it, say — would appear in NO static file. The
 *     first surface alone would pass while the browser was handed the key on
 *     every request. So the pages get fetched and searched too.
 *
 * Markers are used instead of real values so the check runs without secrets and
 * so a hit is unambiguous rather than a lucky match on some base64 string.
 */

import { execFileSync, spawn } from 'node:child_process';
import { createHmac } from 'node:crypto';
import { existsSync, readdirSync, readFileSync, statSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { setTimeout as sleep } from 'node:timers/promises';
import { fileURLToPath } from 'node:url';

const APP = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const PORT = 4399;

const MARKERS = {
  SITE_PASSWORD: 'MARKER-SITE-PASSWORD-a1b2c3',
  SUPABASE_URL: 'https://MARKER-SUPABASE-URL-d4e5f6.supabase.co',
  SUPABASE_SERVER_READ_KEY: 'sb_secret_MARKER-READ-KEY-g7h8i9',
};

/** Static output only. Function chunks run on the server and may hold the key. */
const BROWSER_REACHABLE = ['.vercel/output/static', 'dist/client'];

function filesUnder(dir: string): string[] {
  if (!existsSync(dir)) return [];
  const found: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) found.push(...filesUnder(full));
    else found.push(full);
  }
  return found;
}

function findIn(haystack: string, where: string): string[] {
  return Object.entries(MARKERS)
    .filter(([, marker]) => haystack.includes(marker))
    .map(([name]) => `${name} -> ${where}`);
}

/** Mirrors lib/auth.ts, so the home page can be fetched past the gate. */
function cookieFor(password: string): string {
  return createHmac('sha256', password).update('dolarito-session-v1').digest('hex');
}

async function checkRenderedPages(): Promise<string[]> {
  // Not bound: the handle is never used, because the server is stopped through
  // `astro dev stop` rather than by signalling this process.
  spawn('npx', ['astro', 'dev', '--port', String(PORT)], {
    cwd: APP,
    env: { ...process.env, ...MARKERS },
    stdio: 'ignore',
    shell: true,
    detached: false,
  });

  try {
    // Poll rather than sleep blindly: a fixed wait is either slow or flaky.
    let ready = false;
    for (let attempt = 0; attempt < 40 && !ready; attempt += 1) {
      await sleep(500);
      try {
        await fetch(`http://localhost:${PORT}/entrar`);
        ready = true;
      } catch {
        // not up yet
      }
    }
    if (!ready) throw new Error(`dev server did not answer on ${PORT}`);

    const cookie = `dolarito_acceso=${cookieFor(MARKERS.SITE_PASSWORD)}`;
    const leaks: string[] = [];

    for (const path of ['/entrar', '/']) {
      const response = await fetch(`http://localhost:${PORT}${path}`, { headers: { cookie } });
      const html = await response.text();
      console.log(`  fetched ${path.padEnd(8)} ${response.status}  ${html.length} bytes`);
      leaks.push(...findIn(html, `rendered HTML of ${path}`));
    }

    return leaks;
  } finally {
    execFileSync('npx', ['astro', 'dev', 'stop'], { cwd: APP, stdio: 'ignore', shell: true });
  }
}

async function main(): Promise<void> {
  console.log('building with marker values...');
  execFileSync('npx', ['astro', 'build'], {
    cwd: APP,
    env: { ...process.env, ...MARKERS },
    stdio: 'pipe',
    shell: true,
  });

  const files = BROWSER_REACHABLE.flatMap((dir) => filesUnder(join(APP, dir)));
  console.log(`\n1. static assets: searching ${files.length} file(s)`);
  const staticLeaks = files.flatMap((file) =>
    findIn(readFileSync(file, 'latin1'), file.slice(APP.length + 1)),
  );

  console.log('\n2. rendered HTML: starting a server with the markers set');
  const htmlLeaks = await checkRenderedPages();

  const leaks = [...staticLeaks, ...htmlLeaks];
  console.log('');

  for (const name of Object.keys(MARKERS)) {
    const hits = leaks.filter((leak) => leak.startsWith(name));
    if (hits.length === 0) console.log(`  ✔ ${name.padEnd(26)} reaches no browser`);
    else console.error(`  ✖ ${name.padEnd(26)} LEAKED (${hits.length})`);
  }

  if (leaks.length > 0) {
    console.error('\nCREDENTIAL LEAK:');
    for (const leak of leaks) console.error(`  - ${leak}`);
    process.exitCode = 1;
    return;
  }

  console.log('\nNo credential reaches the browser, in assets or in rendered pages.');
}

await main();
